#!/bin/bash
# SmolVLA Real Integration Testing - Complete Runbook
# 
# This file documents the EXACT steps to start the real integration tests
# with your Colab SmolVLA server.

echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║           SmolVLA Real Integration Testing (Gate 4b + 5)               ║"
echo "║                                                                        ║"
echo "║  This script will:                                                    ║"
echo "║  1. Guide you to start Colab server                                   ║"
echo "║  2. Extract the ngrok URL                                             ║"
echo "║  3. Run Gate 4b tests (13 real VLA integration tests)                 ║"
echo "║  4. Run Gate 5 tests (12 full E2E system tests)                       ║"
echo "║                                                                        ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"

echo ""
echo "📋 PREREQUISITE CHECKLIST"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "Before running tests, ensure:"
echo "  □ Colab notebook is open (vla/smolvla_server.ipynb)"
echo "  □ GPU is enabled (Runtime → Change runtime type → T4 GPU)"
echo "  □ Cells 1-18 are executed (should be already done)"
echo "  □ ngrok auth token is set in Cell 6"
echo ""

echo ""
echo "🚀 STEP 1: START COLAB SERVER"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "In Colab notebook (https://colab.research.google.com):"
echo ""
echo "  1. Scroll down to Cell 20 'Setup ngrok and Run Server'"
echo "  2. Click ▶ Run cell"
echo "  3. Wait for output: 'Server running. Press Ctrl+C to stop.'"
echo ""
echo "  Expected output will show:"
echo "    🌐 PUBLIC SERVER URL (use in local client):"
echo "       https://xxxx-xxxx-ngrok-free.dev"
echo ""

echo ""
echo "🔗 STEP 2: EXTRACT NGROK URL AND RUN TESTS LOCALLY"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "In your terminal (this machine):"
echo ""
echo "Option A: Provide URL as argument:"
echo "  python3 scripts/run_real_integration_tests.py 'https://xxxx-xxxx-ngrok-free.dev'"
echo ""
echo "Option B: Run without argument (will prompt for URL):"
echo "  python3 scripts/run_real_integration_tests.py"
echo ""
echo "Option C: Set environment and run tests manually:"
echo "  export SMOLVLA_SERVER_URL='https://xxxx-xxxx-ngrok-free.dev'"
echo "  pytest tests/test_integration_real_smolvla.py tests/test_e2e_gate5.py -v -s"
echo ""

echo ""
echo "📊 EXPECTED TEST RESULTS"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "Gate 4b: Real SmolVLA Integration"
echo "  ✅ Server health endpoint"
echo "  ✅ Single inference"
echo "  ✅ Multiple queries"
echo "  ✅ Non-blocking verification"
echo "  ✅ Gate 4b validation"
echo "  Expected: 13/13 tests PASSED (~2-3 minutes)"
echo ""
echo "Gate 5: E2E System Testing"
echo "  ✅ Point-to-point reaching"
echo "  ✅ Sequential tasks"
echo "  ✅ Concurrent operations"
echo "  ✅ Async polling thread"
echo "  ✅ Stress testing"
echo "  ✅ Gate 5 validation"
echo "  Expected: 12/12 tests PASSED (~3-5 minutes)"
echo ""
echo "TOTAL: 25/25 tests PASSED (~5-10 minutes total)"
echo ""

echo ""
echo "⏱️  TIMING EXPECTATIONS"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "  • Server startup in Colab:        ~2-3 minutes"
echo "  • Health check:                   <1 second"
echo "  • Gate 4b tests:                  ~2-3 minutes"
echo "  • Gate 5 tests:                   ~3-5 minutes"
echo "  ─────────────────────────────────────────"
echo "  TOTAL:                            ~5-10 minutes"
echo ""

echo ""
echo "🔍 VERIFICATION CHECKLIST (While server is running)"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "Test the server manually before running pytest:"
echo ""
echo "1. Export the URL:"
echo "   export URL='https://xxxx-xxxx-ngrok-free.dev'"
echo ""
echo "2. Health check:"
echo "   curl -X GET \"\$URL/health\""
echo "   Expected: {\"status\":\"ok\",\"model\":\"smolvla_base\"}"
echo ""
echo "3. Verify in Python:"
echo "   python3 -c \"import requests; print(requests.get('\$URL/health').json())\""
echo ""

echo ""
echo "⚠️  TROUBLESHOOTING"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "❌ Error: 'SMOLVLA_SERVER_URL not set'"
echo "   Fix: export SMOLVLA_SERVER_URL='https://xxxx-xxxx-ngrok-free.dev'"
echo ""
echo "❌ Error: 'Connection refused'"
echo "   Fix: Check Colab notebook is still running (look for 'Running' indicator)"
echo ""
echo "❌ Error: 'Timeout' or 'No response'"
echo "   Fix: Check ngrok URL is correct (copy again from Cell 21)"
echo ""
echo "❌ Tests run but all fail"
echo "   Likely: Colab GPU degraded or model loading failed"
echo "   Fix: Restart Colab kernel (Runtime → Restart runtime) and re-run cells 20-21"
echo ""

echo ""
echo "✅ SUCCESS CRITERIA"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "Gate 4b: PASSED ✅"
echo "  • Server health check succeeds"
echo "  • Real inference returns valid actions"
echo "  • Multiple queries work reliably"
echo "  • MPC timing unaffected by VLA latency"
echo ""
echo "Gate 5: PASSED ✅"
echo "  • Reaching task executes successfully"
echo "  • Concurrent MPC+VLA operations work"
echo "  • Background polling thread is stable"
echo "  • Stress test completes (2 minutes continuous)"
echo ""

echo ""
echo "📚 REFERENCE DOCS"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "  • Setup guide: docs/REAL_SMOLVLA_SETUP.md"
echo "  • Status report: docs/PHASE_7_8B_STATUS_REAL_INTEGRATION.md"
echo "  • Quick start: QUICK_START_REAL_INTEGRATION.md"
echo "  • Colab checklist: COLAB_STARTUP_CHECKLIST.md"
echo ""

echo ""
echo "🎯 NEXT STEPS AFTER TESTS PASS"
echo "─────────────────────────────────────────────────────────────────────────"
echo ""
echo "1. ✅ Gate 4b tests pass (real VLA integration working)"
echo "2. ✅ Gate 5 tests pass (full system validated)"
echo "3. 📋 Phase 9: Performance tuning (8-10 hours)"
echo "   • Profile MPC solver"
echo "   • Optimize trajectory interpolation"
echo "   • Measure end-to-end latency"
echo ""
echo "4. 📋 Phase 10: Observability (4-6 hours)"
echo "   • Create live dashboard"
echo "   • Structured JSON logging"
echo "   • Final documentation"
echo ""

echo ""
echo "═════════════════════════════════════════════════════════════════════════"
echo "                  Ready to start real integration testing! 🚀"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
